//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessSA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLUJO
    {
        public FLUJO()
        {
            this.TAREAS_TIPO = new HashSet<TAREAS_TIPO>();
        }
    
        public decimal ID_FLUJO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<TAREAS_TIPO> TAREAS_TIPO { get; set; }
    }
}
