//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessSA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREAS_TIPO
    {
        public TAREAS_TIPO()
        {
            this.TAREA = new HashSet<TAREA>();
        }
    
        public decimal ID_TAREAS_TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO_TAREA_TIPO { get; set; }
        public decimal FLUJO_ID_FLUJO { get; set; }
    
        public virtual FLUJO FLUJO { get; set; }
        public virtual ICollection<TAREA> TAREA { get; set; }
    }
}
