//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessSA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        public decimal ID_TAREA { get; set; }
        public System.DateTime FECHA_PLAZO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
        public string ESTADO_AVANCE { get; set; }
        public decimal ID_RESPONSABLE { get; set; }
        public Nullable<decimal> ID_TAREA_DEPENDENCIA { get; set; }
        public string JUSTIFICACION { get; set; }
        public string ESTADO { get; set; }
        public string REPORTE { get; set; }
        public decimal TAREAS_TIPO_ID_TAREAS_TIPO { get; set; }
        public string USUARIOS_NOMBRE_USUARIO { get; set; }
    
        public virtual TAREAS_TIPO TAREAS_TIPO { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
