//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessSA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDAD
    {
        public UNIDAD()
        {
            this.JERARQUIA = new HashSet<JERARQUIA>();
        }
    
        public decimal ID_UNIDAD { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<JERARQUIA> JERARQUIA { get; set; }
    }
}
