//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessSA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.TAREA = new HashSet<TAREA>();
        }
    
        public decimal RUT { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_P { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public decimal ROL_ID_ROL { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONO { get; set; }
        public decimal JERARQUIA_ID_JERARQUIA { get; set; }
    
        public virtual JERARQUIA JERARQUIA { get; set; }
        public virtual ROL ROL { get; set; }
        public virtual ICollection<TAREA> TAREA { get; set; }
    }
}
